### PR TITLE
control_readfile() called with less arguments

### PR DESCRIPTION
**Pull request by mbhangui**
control_readfile() function in control.c requires 3 arguments - a stralloc variable, filename, flagme. It is being called with just two arguments in qmail-showctl.c

### CODE REVIEW

**Comment by schmonz** [comment]
I was hoping to merge this, but GitHub didn't do what I wanted. @mbhangui, can you rebase your `qmail-showctl-bug` onto the latest `master` and force-push your branch?

**Comment by mbhangui** [comment]
@schmonz now that it has been merged, should I delete this branch?

**Comment by alanpost** [comment]
@mbhangui, you used the merge button to put this PR on master.  This was incorrect.  You should have used the rebase button, which is available from the drop-down menu just to the right of the big green merge button.  That is what @schmonz was asking you to do: rebase the existing master on to the qmail-showctl-bug branch so that the qmail-showctl-bug branch could then itself be rebased on to master.  That gets the change on to master without an unnecessary merge commit.  We use a rebase workflow for master.

I have corrected the issue this time by force pushing just your commit over the two merge commits created when you approved your change.  This requires special effort.  Please read up on rebasing and if you have any questions please ask for help.  git has a frustrating learning curve.

Here is what you should have done:

    # make sure you're on the correct branch.
    $ git checkout qmail-showctl-bug

    # take all changes on master since you created the branch,
    # leaving your branch changes on top.  You may have to
    # resolve merge conflicts.
    $ git rebase master

    # with your branch being all of master plus your change and
    # nothing else, force push to update the PR, which will allow
    # it to be rebased on to master when it is ready.
    $ git push --force

Once a change is approved and ready to put on master, and from the GitHub interface, never use the merge button, but select the rebase button from the drop down menu instead on the merge button instead.

Finally, I am really happy your first commit is now on master, in time for our first release.  Great catch.

**Comment by mbhangui** [comment]
​Oops. Next time I am going to confirm with one of you before doing something. Looks like I have much reading to do on git. Sorry for the trouble caused

**Comment by alanpost** [comment]
There was no lasting trouble, and a very good fix came from it.  I'm sorry git is so irksome.

**Comment by DerDakon** [comment]
It's not git, just the Github UI tricking you here.

**Pull request merged**
