### PR TITLE
1.09 release commits

### PR DESCRIPTION
**Pull request by schmonz**

### CODE REVIEW

**Review by mbhangui — APPROVED** [review]

**Review by DerDakon — APPROVED** [review]

**Comment by DerDakon** [comment]
Needs https://github.com/notqmail/notqmail/pull/246 to fix the build first.

**Review by josuah — APPROVED** [review]
Thank you all, for this amazing continued effort!
This CHANGES.md goes back all the way up to 1996, and still around today!

**Comment by josuah** [comment]
Good idea to also document the CI changes, this can be insightful for someone interested in notqmail.

**Review by leahneukirchen — APPROVED** [review]

**Comment by DerDakon** [comment]
> Good idea to also document the CI changes, this can be insightful for someone interested in notqmail.

I would actually see it the other way 'round: a user of the release tarball does not care for that, as those files are not shipped with the tarballs anyway.

**Pull request merged**
