### PR TITLE
Point SMTP HELP at notqmail's home page.

### PR DESCRIPTION
**Pull request by schmonz**

### CODE REVIEW

**Comment by alanpost** [comment]
> Please use https://

@schmonz I'm happy to pull you through using acme-tiny to get a Let's Encrypt cert issues for notqmail.org.  It's tractable to describe the steps and help debug over IRC.

**Comment by schmonz** [comment]
acme-tiny is exactly what I use. Done :-)

**Comment by alanpost** [comment]
I've filed issue #42, regarding the redirect status code returned by this URL.

**Comment by alanpost** [comment]
This branch needs a rebase to bring in the fix commit for the Mac OS X work, PR #40.

**Pull request merged**
