### PR TITLE
Add acknowledgement for the bug fix contribution to qmail-local.c

### PR DESCRIPTION
**Pull request by eriksjolund**
Reference:
https://web.archive.org/web/20060411195013/http://www.ornl.gov/lists/mailing-lists/qmail/2000/10/msg00696.html

Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>

### CODE REVIEW

**Comment by DerDakon** [comment]
In general: yes. I'm just unsure if this belongs at that place in the README, because the actual contribution was to nEtqmail.

**Comment by DerDakon** [comment]
If that way is fine with you: I'm all for it. Please just squash these 2 commits together.

**Comment by eriksjolund** [comment]
It looks good to me. Thanks

**Comment by schmonz** [comment]
Since we seem to be the git repo of record, I'm all for this. Thanks, @eriksjolund!

**Pull request merged**
