### PR TITLE
debug solaris makefile syntax issue

### PR DESCRIPTION
**Pull request by josuah**
any better way to debug it?

### CODE REVIEW

**Comment by DerDakon** [comment]
Could you just turn this into a normal PR, changing only the Makefile and adding a comment about why this is needed? This could ease getting in other things, as more branches get affected by this.

**Comment by DerDakon** [comment]
Doesn't help, see https://github.com/notqmail/notqmail/runs/1796785277?check_suite_focus=true

**Comment by josuah** [comment]
I assumed I understood why it did work and attempted something that looks less weird.
I pushed the original version back but I do not understand what is going on.
Waiting code check and pinging back on IRC.

**Comment by schmonz** [comment]
Do we remember what the error(s)/problem(s) looked like? In my testing for #231, I saw and fixed:

- `make man` getting an empty value of `NROFF`, despite `NROFF?=nroff`
- `make clean` and `make test` not working (#203)

Was there anything further?

**Comment by schmonz** [comment]
This was almost certainly solved by #231. Please reopen (or file a new issue) if I missed something.

**Pull request closed without merging**
